### ISSUE TITLE
request-replay returning null!

### ISSUE THREAD

**Issue by RadhaR4** [IndigoUnited/node-request-replay#4]
This is the code I am trying out with request-replay.
var fs = require('fs');
var request = require('request');
var replay = require('request-replay');
// Note that the options argument is optional
// Accepts the same options the retry module does and an additional
// errorCodes array that default to ['EADDRINFO', 'ETIMEDOUT', 'ECONNRESET', 'ESOCKETTIMEDOUT']
replay(request('http://googldsdse.com/doodle.png', function (err, response, body) {
    // Do things
    console.log(response);
}), {
    retries: 10,
    errorCodes: ['NOTFOUND',
    'EADDRINFO',
    'ETIMEDOUT',
    'ECONNRESET',
    'ESOCKETTIMEDOUT',
    'ENOTFOUND'],
    factor: 3
})
.on('replay', function (replay) {
    // "replay" is an object that contains some useful information
    console.log('request failed: ' + replay.error.code + ' ' + replay.error.message);
    console.log('replay nr: #' + replay.number);
    console.log('will retry in: ' + replay.delay + 'ms')
})

This code is returning expected output for one person as shown in the image below,
![image](https://cloud.githubusercontent.com/assets/14121261/9697160/c56cd17c-539f-11e5-913f-88d6d3e8010b.png)

But When I am trying the same code,its just returning the entire response only once.Not entering into replay event.If I try to print console.log(err),its returning NULL.
![image](https://cloud.githubusercontent.com/assets/14121261/9697167/08561d7c-53a0-11e5-9a02-052a867bf23e.png)

I event tried to reinstall request-replay.
F:\Techie\Nodejs>npm uninstall request-replay
unbuild request-replay@0.3.0
F:\Techie\Nodejs>npm install request-replay
request-replay@0.3.0 node_modules\request-replay
└── retry@0.6.1
F:\Techie\Nodejs>

But same issue persists.Please let me know what could be the issue.

**Comment by RadhaR4** [comment]
I tried in Linux and Windows.Version of node.js I am using is 0.10.40.Its showing the entire response instead of the expected replay response.Please help to resolve this issue.

**Comment by satazor** [comment]
The code works as expected in my environment, I'm using node 0.12.x on MacOSx. The only reason it doesn't work for you is that your router might be doing some trickery when accessing web pages of unknown hosts. Can you open http://googldsdse.com/doodle.png in your browser and see the response you get (also check the response in devtools). Can you please take a screenshot and post it here?

**Comment by RadhaR4** [comment]
Thanks for looking into this issue.
Here is the screenshot captured with devtools Network trace.Please let me know if you need anymore details.
![reqrep-error](https://cloud.githubusercontent.com/assets/14121261/10271676/1eccb896-6b32-11e5-82b3-9542fac579b0.png)

**Comment by satazor** [comment]
As I expected the problem is that your routet is intercepting the request (port 80) and instead of failing is returning a valid 200 Ok response as seen in the screenshot. 

There's nothing I can do in my side but ypu should research if its possible to disable that "feature" in your router.
